const getData = async () => {
    try {
      const response = await fetch();
    }
    catch(error) {
      console.log(error);
    }
  }